#!/bin/bash

#/ NAME
#/     edit-today -- edit today's article
#/
#/ SYNOPSIS
#/     edit today

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main {
  ${EDITOR:-vi} $shome/content/articles/$(date +%Y%m%d).md
}

require sub "$BASH_SOURCE" "$@"
