#!/bin/bash

#/ NAME
#/     new-article -- new daily blog post
#/
#/ SYNOPSIS
#/     new article

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main {
  mkdir -p $shome/content/articles
  touch $shome/content/articles/$(date +%Y%m%d).md
  echo "---" > $shome/content/articles/$(date +%Y%m%d).yaml
}

require sub "$BASH_SOURCE" "$@"
